[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "skale.py"
version = "7.14"
description = "SKALE client tools"
readme = "README.md"
requires-python = ">=3.11,<4"
license = { text = "AGPL-3.0-or-later" }
authors = [{ name = "SKALE Labs", email = "support@skalelabs.com" }]
keywords = ["skale"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "redis>=7.2.0",
    "sgx.py==0.11",
    "skale-contracts==2.0.0a12",
    "skale.py-core",
    "typing-extensions==4.15.0",
    "web3==7.15.0",
    "multisigwallet-predeployed==1.1.0b0",
]

[project.optional-dependencies]
linter = ["ruff==0.15.12", "mypy==1.20.2"]
hw-wallet = ["ledgerblue==0.1.56"]
dev = [
    "skale.py[linter,hw-wallet]",
    "codecov",
    "freezegun==1.5.5",
    "mock==5.2.0",
    "pytest==9.0.3",
    "pytest-cov==7.1.0",
    "pytest-timeout==2.4.0",
    "types-requests",
    "types-redis",
]

[project.urls]
Homepage = "https://github.com/skalenetwork/skale.py"


[tool.uv]
prerelease = "allow"

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
"skale.py-core" = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["skale"]
only-include = ["skale"]

[tool.hatch.build.targets.wheel.shared-data]
"skale/py.typed" = "skale/py.typed"

[tool.pytest.ini_options]
addopts = ["--timeout=30", "--timeout-method=thread"]
log_cli = false
log_cli_level = "WARNING"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
filterwarnings = ["ignore::DeprecationWarning"]

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
ignore_missing_imports = true

[tool.ruff]
line-length = 100
exclude = ["helper-scripts", ".git"]
target-version = "py314"

[tool.ruff.lint]
select = ["E", "W", "F", "I"]

[tool.ruff.format]
quote-style = "single"
