name: Test
on: [push, pull_request]

env:
  ETH_PRIVATE_KEY: ${{ secrets.ETH_PRIVATE_KEY }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  ENDPOINT: "http://127.0.0.1:8545"
  MANAGER_TAG: "1.12.0-develop.21"
  MINING_INTERVAL: 10
  ALLOCATOR_TAG: "2.2.2-develop.0"
  MIRAGE_TAG: "1.0.0-develop.0"

jobs:
  common:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: bash ./scripts/install_python_dependencies.sh

      - name: Lint with ruff
        run: ruff check skale/

      - name: Launch hardhat node
        working-directory: hardhat-node
        run: |
          docker compose up -d && sleep 20

  test_manager:
    needs: common
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Deploy manager
        run: |
          bash ./helper-scripts/deploy_manager.sh
          docker rmi -f skalenetwork/skale-manager:${{ env.MANAGER_TAG }}

      - name: Run tests
        run: |
          bash ./scripts/run_manager_tests.sh
      - name: Codecov
        run: |
          codecov -t $CODECOV_TOKEN

  test_allocator:
    needs: common
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Deploy manager contracts
        run: |
          bash ./helper-scripts/deploy_manager.sh
          docker rmi -f skalenetwork/skale-manager:${{ env.MANAGER_TAG }}

      - name: Deploy allocator contracts
        run: |
          bash ./helper-scripts/deploy_allocator.sh
          docker rmi -f skalenetwork/skale-allocator:${{ env.ALLOCATOR_TAG }}

      - name: Run tests
        run: |
          bash ./scripts/run_allocator_tests.sh

